app = "zhorben-pamyataj-9745fb9a-0ee5-44a4-a407-1e8c628514cd"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'
DEPLOY_ID = 'ac20684a-c1fd-4493-8c24-40376c4483ab'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
